### ISSUE TITLE
New Feature - Assign a award to a complete Role by batch processing

### ISSUE THREAD

**Issue by pphlwmarcel** [sistlind/awards#1]
I have just looked for a possibility to assign a award to a whole role in one step.
As you can See in the File awards_change.php I have implemented the requested feature.

For better handling - and the possibility to disable the new feature - I have also implemented a config.php, so maybe there is a future use as well to change some other settings easily.

I also added some color and symbols to the script, to have a better optrical echo for the user

If you are looking for the comment Line /\* MSC Anfang - Bemerkung für Entwickler */ you can find the changes I made fast.

An onther enhancement I made you can find in Line 551: Because the option as spacer had the value -1 there was an undefined error if the user submit with this option. So if you remove the value there is the right error shown (no input for Award given)

If you have any questions you can contact me (in English or German)
[awards_change.php.txt](https://github.com/sistlind/awards/files/53932/awards_change.php.txt)
[config.php.txt](https://github.com/sistlind/awards/files/53933/config.php.txt)

**Comment by pphlwmarcel** [comment]
for the new feature there is also a updated language file available

**Comment by sistlind** [comment]
Hi,
ich werde es mir einmal anschaun und höchstwahrscheinlich auch übernehmen.
Kannst du mir bitte noch ein Beispiel nennen, wo man einer ganzen Rolle
eine Ehrung gibt?

Bitte schicke mir auch noch das language file.

Gruß Stefan

2015-12-07 13:52 GMT+01:00 Marcel notifications@github.com:

**Comment by pphlwmarcel** [comment]
Hallo Stefan,

anbei die language files. 

Was genau meinst du mit einem Beispiel? 
Ich setze das Plugin zur Lehrgangsverwaltung ein. Die Teilnehmer sind bei uns in einer Rolle zusammengefasst um Mails an alle Teilnehmer versenden zu können, Teilnahmelisten zu erstellen, ect. Nach Abschluss des Lehrgangs können wir dann direkt aus der Rolle mit einem Klick allen (außer dem Seminarleiter natürlich) den Lehrgang im Plugin zuweisen.
Ich denke für Sportvereine zum Beispiel an die Verleihung eines Meisterschaftstitel an die komplette Manschaft (inklusive Trainer) oder ähnliches. Kommt ganz auf die Organisation an, die das Plugin einsetzt.

[Changelog.txt](https://github.com/sistlind/awards/files/54274/Changelog.txt)
[de.xml.txt](https://github.com/sistlind/awards/files/54264/de.xml.txt)
[de_sie.xml.txt](https://github.com/sistlind/awards/files/54265/de_sie.xml.txt)
[en.xml.txt](https://github.com/sistlind/awards/files/54266/en.xml.txt)

**Comment by sistlind** [comment]
Hi,
bin jetzt mal dazugekommen und es einzubauen. Ein paar Kleinigkeiten habe ich noch gefixed und die Standardwerte erst einmal auf das alte verhalten angepasst.

Dass nächste mal bitte direkt als Pullrequest schicken, spart nen Haufen Arbeit :)
Trotzdem vielen Dank für den Beitrag, sind denke ich sinnvolle änderungen.

Gruß Stefan
