### ISSUE TITLE
Löschen von Titel-Einträgen und Sortierung

### ISSUE THREAD

**Issue by WeT-Klb** [sistlind/awards#10]
Hallo,

ist es möglich, die "Früheren Titel" zu bearbeiten? Im Laufe der Zeit haben sich Vervielfältigungen der Titel angehäuft, da teilweise neue Titel angelegt wurden, obwohl "Frühere Titel" entsprechend vorhanden waren. 
Somit existieren z.B mehrfach die Titel "Weißgurt". 
Könnte man nicht auch einen Abgleich im Plugin erzeugen, der prüft, ob ein neu anzulegender Titel bereits existent ist und somit eine Neuanlage unterbinden?

Eine weitere Frage ist, ob man die Sortierung automatisieren kann bzw. ob man auch manuell die Anzeigereihenfolge der Einträge anpassen kann.
Ein Beispiel: Bei uns im Karateverein hat jemand Weiß- und Gelbgurt am gleichen Tag gemacht. Jetzt wird der Eintrag "Gelbgurt" aber nach oben gesetzt, da ja "G" vor "W" (Weißgurt) kommt und außerdem wird noch die Kategorie ausgewertet (All Style Karate bzw. Kickboxen). Es wäre schön, wenn man hier die Reihenfolge händisch anpassen könnte, man also den Eintrag verschieben könnte.

![Titel](https://user-images.githubusercontent.com/20600342/191220413-f383c3eb-71bb-4a89-9c17-def708f62c3e.jpg)
![Sortierung](https://user-images.githubusercontent.com/20600342/191220406-0752b6cb-52b4-4a66-82f7-6cd447ce4608.jpg)

**Comment by sistlind** [comment]
Hallo, wie bereits per Mail beschrieben, eine Löschung der Einträge ist nicht möglich, sie werden nicht extra gepflegt sondern direkt aus den vorhandenen Datensätzen generiert.
Die Einträge sollte natürlich trotzdem nur einzeln auftreten. Der Fehler liegt vermutlich an den Sonderzeichen/Umlauten. Das schaue ich mir an
