### ISSUE TITLE
White Screen on Amidio v4.2.4

### ISSUE THREAD

**Issue by HB9HIL** [sistlind/awards#12]
White Screen of the Amidio Instance after adding de DIV Block to `admidio/adm_themes/simple/templates/overview.tpl`

`<div class="admidio-overview-plugin col-sm-6 col-lg-4 col-xl-3" id="admidio-plugin-awards">`
`        <div class="card admidio-card">`
`            <div class="card-body">`
`                {load_admidio_plugin plugin="awards" file="awards.php"}`
`            </div>`
`        </div>`
`    </div>`

Amidio v4.2.4
Awards v2.0.0

**Comment by Rvice** [comment]
If this is added as per the INSTALL.txt it shows. Not that it's correct for 4.2.4
