### ISSUE TITLE
"Diese Seite funktioniert im Moment nicht" bei Awards 2.0.0 und Admidio ab 4.3.1

### ISSUE THREAD

**Issue by WeT-Klb** [sistlind/awards#14]
Ich habe mit Einführung von Admidio 4.3.1 das Problem, daß beim Aufruf von "Ehrungen anzeigen" auf der linken Seite unter "PLUGINS" die Meldung "Diese Seite funktioniert im Moment nicht. HTTP ERROR 500" erscheint und ich auf der Seite 

adm_plugins/awards/awards_show.php 

verbleibe.

Ich habe auch 

"include_once(ADMIDIO_PATH . FOLDER_PLUGINS .'/awards/awards_profile_addin.php');" 

in der 

adm_program/modules/profile/profile.php 

VOR 

$page->show(); 

eingefügt. Die Anzeige der Ehrungen im Profil des Mitglieds selbst funktioniert damit tadellos.

**Comment by sistlind** [comment]
Sollte mit commit 711368c gefixed sein
