### ISSUE TITLE
4.3.3 Incompatible?

### ISSUE THREAD

**Issue by Rvice** [sistlind/awards#15]
I'm getting the following error

Fatal error: Uncaught TypeError: Argument 2 passed to HtmlNavbar::__construct() must be of the type string, null given, called in /admidio/adm_plugins/awards/awards_show.php on line 201 and defined in /admidio/adm_program/system/classes/HtmlNavbar.php:79 Stack trace: #0 /admidio/adm_plugins/awards/awards_show.php(201): HtmlNavbar->__construct('menu_list_filte...', NULL, NULL, 'filter') #1 {main} thrown in /admidio/adm_program/system/classes/HtmlNavbar.php on line 79

Looks like the new version of Admidio (4.3.3) is not supported

**Comment by Rvice** [comment]
Inserting '' on both lines instead of null

line 201: `$filterNavbar = new HtmlNavbar('menu_list_filter', '', null, 'default');`
line 392: `$table->addRowByArray($columnValues, '', array('nobr' => 'true'));`

This at least has the form load, it's not showing all the awards though like before. Selecting individual awards does show correctly though. So must be something on the initial sort.

**Comment by WeT-Klb** [comment]
Did you somwhow manege to make it work? I tried your "workaround" - but only works for a part of seconds then i get the message again. Before the message maybe for a half second the list will appear as expected.

**Comment by sistlind** [comment]
Sollte mit commit https://github.com/sistlind/awards/commit/711368cd622668f278cdc44b1bb60f0a7e225e7e gefixed sein
