### ISSUE TITLE
Hilfe bei Problemen

### ISSUE THREAD

**Issue by Ruckhaber** [sistlind/awards#2]
Bekommt man hier Hilfe zum Admidio Plugin Awards?

Gruß Ruckhaber

**Comment by sistlind** [comment]
ja

Am 30.09.2016 11:06 schrieb "Ruckhaber" notifications@github.com:

**Comment by Ruckhaber** [comment]
Ich habe Admidio und unter anderem das Awards-Plugin installiert.
Wenn ich beim Benutzen des Plugins „Ehrung zuweisen“ wähle, erhalte ich folgende SQL-Fehlermeldung.
CODE: 42000
1055

Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'usr_web1219_2.adm_user_awards.awa_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

B A C K T R A C E
ILE: adm_program/system/classes/database.php
LINE: 433
CALL: Database->showError()

FILE: adm_plugins/awards/awards_change.php
LINE: 470
CALL: Database->query()

Was hat es mit dieser Fehlermeldung auf sich?

P.S. Auf der Admidio-Webseite wird für das Awards-Plugin auf eine email-Adresse des Betreuers hingewiesen. Der Link ist anscheinend mit einer fehlerhaften Email-Adresse verbunden.

Viele Grüße
Ruckhaber

**Comment by sistlind** [comment]
Welche admidio version verwendest du? falls 3.1.7/3.2.0 hat sich
wahrscheinlich mal wieder etwas an der datenbank api geändert. dass mit den
sql-groups dagt mir gar nichts.

gruß Stefan

Am 30.09.2016 12:44 schrieb "Ruckhaber" notifications@github.com:

**Comment by Ruckhaber** [comment]
Admidio-Version Installiert: 3.1.7
PHP-Version: 7.0.11
MySQL-Version: 5.7.14
Safe Mode: aus
max. POST-Größe: 8M
Arbeitsspeicher: 64M
Dateiuploads: an
max. Uploadgröße: 8M

Von einer Version 3.2.0 habe ich noch gar nichts gesehen.

Gruß Jörn

**Comment by sistlind** [comment]
Die Emailadresse auf der Admidio homepage ist schon korrekt.

Ich wollte am Wochenende meine installation auf 3.1.7 upgraden. Dabei wollte sich die Datenbank auf 3.2.0beta upgraden. Deshalb die Aussae zu 3.2.0.

Leider ging bei mir schon das Datenbankupgrade schief und ich bin deshalb noch auf 3.1.6.
Ich werde es am Wochenende noch einmal versuchen und sobald ich auf 3.1.7 bin den Fehler suchen und fixen. Ich vermute die Admidio-Entwickler haben mal wieder irgendwelche tollen neuen Sicherheitsfeatures eingebaut und natürlich die Plugin-Entwickler nicht informiert :(

Wenn du möchstest kanst du den Fehler auch direkt einmal im Forum posten, eventuell muss ich das sowieso, da sich wahrscheinlich irgendwas an der API geändert hat.

Gruß Stefan

**Comment by Ruckhaber** [comment]
OKAY, dann bin ich mal vorsichtig optimistisch, dass der Fehler gefunden wird.

Ich habe versucht Dir über diese Adresse eine Email zu senden. Das hat mein Server ausgespuckt:

Ihre Nachricht hat einige oder alle Empfänger nicht erreicht.
      Betreff:  Admidio
      Gesendet am:  30.09.2016 08:53

Folgende(r) Empfänger kann/können nicht erreicht werden:

```
  'mailto:stefan.lindner@gmail.com' am 30.09.2016 08:53
        Serverfehler: "Ungültiger Empfänger"'
```

Gruß Jörn

**Comment by sistlind** [comment]
Hi,
also habe jetzt das Update hinbekommen, leider funktioniert bei mir das awards plugin aber einwandfrei :/
Es könnte sein, dass der Fehler im zusammenhang mit deiner phpversion steht. Das kann ich mangeld php7 bei meinem Webhoster aber schlecht testen.
Bei mir siehts so aus:

```
Admidio-Version.1.7 
PHP-Version 5.3.28
MySQL-Version5.1.72-2
Safe Mode aus
max. POST-Größe 96M
Arbeitsspeicher 128M
Dateiuploads an
max. Uploadgröße 50M
max. bearbeitbare Bildgröße 17.9 Mega Pixel
Debugmodus aus

```

Gruß Stefan
PS: das mailto: gehört nicht zur Email-Adresse. Werde das mal versuchen zu reparieren.

**Comment by sistlind** [comment]
Ok, deine neue MySQL Version ist das problem, siehe zB hier:
http://stackoverflow.com/questions/37951742/1055-expression-of-select-list-is-not-in-group-by-clause-and-contains-nonaggr

Sobald ich das verstanden habe, versuche ich die Abfragen anzupassen :)

**Comment by sistlind** [comment]
So, war doch einfacher als gedacht. Problem sollte in der git-version gefixed sein. Du musst nur eine Zeile in der awards_change.php korrigieren:
https://github.com/sistlind/awards/commit/288f1a6e2489152e57df1bb13b17742d684bf97b

Gruß Stefan
