### ISSUE TITLE
blank page on loading awards_change.php

### ISSUE THREAD

**Issue by pphlwmarcel** [sistlind/awards#6]
I have updated my admidio from version 3.0.1 to 3.3.1 and updated awards from 0.4.0 to 0.6.0.
If I try to add/change a award (awards_change.php) there is only a blank page without any php warning or something else.
I tryed several php versions to see if there is something wrong with PHP but no success.

**Comment by sistlind** [comment]
Do you have access to the errorlog of your webserver? Turning on the admidio debug mode could also help.

Does the awards_show.php work?

**Comment by pphlwmarcel** [comment]
At least I have activated errorlog via .htaccess but the logfile is empty.

After turning on the debug Modus on Admidio I get the following error message:
`S Q L - E R R O R

CODE: 42S22

1054

Unknown column 'rol_visible' in 'where clause'

B A C K T R A C E

FILE: adm_program/system/classes/Database.php
LINE: 688
CALL: Database->showError()

FILE: adm_plugins/awards/awards_change.php
LINE: 393
CALL: Database->query()`


The awards_show.php works fine

**Comment by sistlind** [comment]
Hmm, here it works fine with awards 0.6.0 and Admidio 3.3.1. I think it is a problem at the new permission system introduced in this version, because i do not use a column rol_visible, but I will try to have a look at the code and search for the issue. Maybe you should also ask this question at the admidio forum/github account.

By the way, i am using this options at the menu configuration:
![grafik](https://user-images.githubusercontent.com/6959674/39670059-865c84e8-50fc-11e8-8683-1f7b9c876ae0.png)
Maybe "Modulreche" needs to be filled

**Comment by pphlwmarcel** [comment]
After some further testing I found out that the following lines are cause the problem. (line 385 -388)
	$sql    = 	'SELECT rol_id, rol_name
	FROM '. TBL_ROLES .'
	WHERE rol_valid =1
	AND rol_visible =1

the "AND rol_visible =1" has to be removed.
The admdio team has removed invisible roles in V 3.3.x so this column isn't available anymore in the database and is bringing the scipt to the issue.

"With version 3.3 we have abolished the invisible roles. Invisible roles were active roles in which the rights were evaluated, but which did not appear in overviews, lists, etc.

Since this was confusing in some places and not consistently used everywhere, we have removed this feature. All invisible roles are visible in the 3.3. You can also achieve the invisible role effect through the available permissions settings of roles." (Announcement for Admidio 3.3)

After removing the wrong line the awards_change.php is working fine again.
So If you have time you can remove the line in your code.

**Comment by sistlind** [comment]
Oh sorry, i did not use th feature to assign awards to whole roles, therefore, there was no error shown at my tests. I will fix it

**Comment by sistlind** [comment]
Fixed in 9dd18d92898074ef5c4244ebc6853bc95e7c4dbf
-> Closed
